// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class BackendBindings
    {
        readonly ICloudCodeService k_Service;
        public BackendBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<string> DeleteAccount(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "DeleteAccount",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> EmailVerification()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "EmailVerification",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<string> GetFirebaseConfig()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "GetFirebaseConfig",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<string> LoadProtectedData(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "LoadProtectedData",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> LoadProtectedGameData(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "LoadProtectedGameData",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<bool> PasswordRecovery(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<bool>(
                "Backend",
                "PasswordRecovery",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task SaveProtectedData(string parametersEncryptedJson)
        {
            await k_Service.CallModuleEndpointAsync(
                "Backend",
                "SaveProtectedData",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task SaveProtectedGameData(string parametersEncryptedJson)
        {
            await k_Service.CallModuleEndpointAsync(
                "Backend",
                "SaveProtectedGameData",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> PurchaseCosmetic(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "PurchaseCosmetic",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> UpdateNationalityAsync(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "UpdateNationalityAsync",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> ClaimMissionReward(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "ClaimMissionReward",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> ValidateMissions()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "ValidateMissions",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<string> UpdateMissionProgress(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "UpdateMissionProgress",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task UpdateCasualMatchAnalytics(string parametersEncryptedJson)
        {
            await k_Service.CallModuleEndpointAsync(
                "Backend",
                "UpdateCasualMatchAnalytics",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> GetLeaderboardEntriesAchievements(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "GetLeaderboardEntriesAchievements",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> GetLeaderboardEntriesPlayerData(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "GetLeaderboardEntriesPlayerData",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> TryToGetNationalityLeaderboard(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "TryToGetNationalityLeaderboard",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> UpdateLeaderboardScoreByMatchResult(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "UpdateLeaderboardScoreByMatchResult",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> RequestPurchase(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "RequestPurchase",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> TryToGetPurchasesData()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "TryToGetPurchasesData",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<string> UpdateProfile(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "UpdateProfile",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> TryToAcceptClubJoiningRequest(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "TryToAcceptClubJoiningRequest",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> TryToDeclineClubJoiningRequest(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "TryToDeclineClubJoiningRequest",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> TryToGetClubChatData(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "TryToGetClubChatData",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> TryToGetClubData(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "TryToGetClubData",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> TryToGetClubLeaderboard()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "TryToGetClubLeaderboard",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<string> TryToOverrideRank(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "TryToOverrideRank",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> TryToRemoveMemberToClub(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "TryToRemoveMemberToClub",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> TryToSearchClubsByName(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "TryToSearchClubsByName",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> TryToSendClubChatMessage(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "TryToSendClubChatMessage",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> TryToSendClubJoiningRequest(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "TryToSendClubJoiningRequest",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> TryToUpdateClubData(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "TryToUpdateClubData",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task SignInIDTokenInFirebase()
        {
            await k_Service.CallModuleEndpointAsync(
                "Backend",
                "SignInIDTokenInFirebase",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task SignInProviderInFirebase(string parametersEncryptedJson)
        {
            await k_Service.CallModuleEndpointAsync(
                "Backend",
                "SignInProviderInFirebase",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task<string> SignInWithCredentials(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "SignInWithCredentials",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task SignUpWithCredentials(string parametersEncryptedJson)
        {
            await k_Service.CallModuleEndpointAsync(
                "Backend",
                "SignUpWithCredentials",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task UpdateDaysStreak()
        {
            await k_Service.CallModuleEndpointAsync(
                "Backend",
                "UpdateDaysStreak",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<string> UpdateTotalTimeMatch(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "UpdateTotalTimeMatch",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task TryToDisableAdsTemporarily()
        {
            await k_Service.CallModuleEndpointAsync(
                "Backend",
                "TryToDisableAdsTemporarily",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task TryToRegisterLastAdSaw()
        {
            await k_Service.CallModuleEndpointAsync(
                "Backend",
                "TryToRegisterLastAdSaw",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<string> ValidateAchievements()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "ValidateAchievements",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<string> ClaimAchievementReward(string parametersEncryptedJson)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Backend",
                "ClaimAchievementReward",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }

        public async Task UpdateAchievementProgress(string parametersEncryptedJson)
        {
            await k_Service.CallModuleEndpointAsync(
                "Backend",
                "UpdateAchievementProgress",
                new Dictionary<string, object>()
                {
                    {"parametersEncryptedJson", parametersEncryptedJson},
                });
        }
    }
}
